name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  #pull_request: disabled, assume that it is working
    #branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v4
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile.backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tooltrack-backend:latest
